matrix:
  include:
#    - language: node_js
#      os:
#        - linux
#      #- osx
#      #- windows
#      node_js:
#        - 13
#      before_script:
#        - cd ts
#      script:
#        - yarn install
#        - yarn test

    - language: rust
      os:
        - linux
      rust:
        - stable
      before_script:
        - cd rs
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all-targets -- -D warnings
        - cargo build
        - cargo test

    - language: rust
      os:
        - linux
      rust:
        - nightly
      before_script:
        - cd rs
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo build
        - cargo test
        - cargo test --all-features

notifications:
  email: false
